# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Testweb' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testweb' do
    @driver.get('https://www.webmotors.com.br/')
    @driver.manage.resize_to(1034, 540)
    element = @driver.find_element(:css, '.CardUltimasBuscas__optionals')
    @driver.action.move_to_element(element).perform
    @driver.find_element(:id, 'searchBar').send_keys('honda city')
    @driver.find_element(:css, '.SearchBar__results__result__name').click
    @driver.execute_script("window.scrollTo(0,200)")
  end
end
